--- #YAML:1.0
name:               CryoTel-CryoCon
version:            0.0.6
abstract:           A module for interfacing with CryoTel Cryocontrollers via TCP
author:
    - Sam Kerr <kerr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
